name: Compress Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compress-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
      
    - name: Cp files
      run: cp ./ LiteLoaderQQNT-Plugin-RepeatMsg

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: LiteLoaderQQNT-Plugin-RepeatMsg
        path: LiteLoaderQQNT-Plugin-RepeatMsg
